nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['*']  # 全局设置
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['*']  # 允许所有头
        expose_headers: ['Link', 'X-Pagination']
        max_age: 3600
        hosts: []
        allow_credentials: false

